version: '2'

services:
  alfresco-core:
    image: ${DOCKER_IMAGE}
    ports:
      - "${DOCKER_IP}:${DOCKER_ALF_PORT}:8080"
    volumes:
    - alfresco:/opt/alfresco/alf_data
    restart: unless-stopped
    environment:
    - DB_NAME=alfresco
    - DB_USERNAME=alfresco
    - DB_PASSWORD=admin
    - DB_URL=jdbc:postgresql://postgresql:5432/alfresco
    - DB_DRIVER=org.postgresql.Driver
    - SOLR_HOST=solr
    - SOLR_PORT=8080
    - SOLR_PORT_SSL=8443
    - JAVA_XMS=511M
    - JAVA_XMX=2048M
    - GLOBAL_content.transformer.RemoteJODConverter.endpoint=http://jodconverter:8080/converter/service
    - GLOBAL_ooo.enabled=false
    - GLOBAL_jodconverter.enabled=false
    - CATALINA_OPTS=-XX:MaxPermSize=256M
    - GLOBAL_audit.enabled = true
    - GLOBAL_audit.alfresco-access.enabled=true
    - GLOBAL_audit.alfresco-access.sub-actions.enabled=true

  solr:
    image: hub.xenit.eu/alfresco-solr1:4.2.8
    volumes:
    - solr:/opt/alfresco/alf_data
    restart: unless-stopped
    environment:
    - ALFRESCO_HOST=alfresco-core
    - ALFRESCO_PORT=8080
    - JAVA_XMS=2G
    - JAVA_XMX=2G

  postgresql:
    image: hub.xenit.eu/postgres:10.4
    volumes:
    - postgres:/var/lib/postgresql/data
    environment:
    - POSTGRES_USER=alfresco
    - POSTGRES_PASSWORD=admin
    - POSTGRES_DB=alfresco
    - "PGCONF_log_line_prefix='%t [%p]: [%l-1] db=%d,user=%u,app=%a,client=%h '"
    - PGCONF_log_checkpoints=on
    - PGCONF_log_connections=on
    - PGCONF_log_disconnections=on
    - PGCONF_log_lock_waits=on
    - PGCONF_log_temp_files=0
    - PGCONF_log_autovacuum_min_duration=0
    - PGCONF_log_error_verbosity=default
    - PGCONF_log_min_duration_statement=100
    restart: unless-stopped

  jodconverter:
    image: hub.xenit.eu/jodconverter-ws
    restart: unless-stopped


volumes:
  alfresco:
  solr:
  postgres:
