version: '2'

services:
  alfresco-core:
    image: ${DOCKER_IMAGE}
    ports:
    - "${DOCKER_IP}:${DOCKER_ALF_PORT}:8080"
    volumes:
    - alfresco:/opt/alfresco/alf_data
    restart: unless-stopped
    environment:
    - SOLR_HOST=solr
    - GLOBAL_audit.enabled = true
    - GLOBAL_audit.alfresco-access.enabled=true
    - GLOBAL_audit.alfresco-access.sub-actions.enabled=true
    # Define mail host settings explicitly for tests involving mailactionexecuter
    - GLOBAL_mail.host=localhost
    - GLOBAL_mail.port=2500

  solr:
    image: hub.xenit.eu/alfresco-enterprise/alfresco-solr6:1.3
    volumes:
    - solr:/opt/alfresco/alf_data
    restart: unless-stopped
    environment:
    - ALFRESCO_HOST=alfresco-core

  postgresql:
    image: xeniteu/postgres
    volumes:
    - postgres:/var/lib/postgresql/data
    environment:
    - POSTGRES_USER=alfresco
    - POSTGRES_PASSWORD=admin
    - POSTGRES_DB=alfresco
    - "PGCONF_log_line_prefix='%t [%p]: [%l-1] db=%d,user=%u,app=%a,client=%h '"
    - PGCONF_log_checkpoints=on
    - PGCONF_log_connections=on
    - PGCONF_log_disconnections=on
    - PGCONF_log_lock_waits=on
    - PGCONF_log_temp_files=0
    - PGCONF_log_autovacuum_min_duration=0
    - PGCONF_log_error_verbosity=default
    - PGCONF_log_min_duration_statement=100
#     - PGCONF_log_duration=on
    restart: unless-stopped
#   authentication-proxy:
#     build:
#         context: nginx-proxy
#     ports:
#       - ${DOCKER_IP}::80
#     restart: unless-stopped
#     command: 'nginx'


  jodconverter:
    image: hub.xenit.eu/public/jodconverter-ws:build-201909241653-3
    restart: unless-stopped


volumes:
  alfresco:
  solr:
  postgres:

