name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:
  workflow_dispatch:

env:
  GRADLE_OPTS: >-
    -Dorg.gradle.project.org.alfresco.maven.nexus.username=${{ secrets.ALFRESCO_NEXUS_USERNAME }}
    -Dorg.gradle.project.org.alfresco.maven.nexus.password=${{ secrets.ALFRESCO_NEXUS_PASSWORD }}
    -Dorg.gradle.project.eu.xenit.artifactory.username=${{ secrets.XENIT_ARTIFACTORY_USERNAME }}
    -Dorg.gradle.project.eu.xenit.artifactory.password=${{ secrets.XENIT_ARTIFACTORY_PASSWORD }}

jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
      - name: Login to Xenit Cloudsmith docker registry
        uses: docker/login-action@v2
        with:
          registry: docker.xenit.eu
          username: ${{ secrets. CLOUDSMITH_USER  }}
          password: ${{ secrets.CLOUDSMITH_APIKEY }}
      - name: Unit tests
        uses: gradle/gradle-build-action@v2.3.0
        with:
          arguments: :c4a-impl:test --info
      - name: Integration tests 6x
        uses: gradle/gradle-build-action@v2.3.0
        with:
          arguments: :c4a-test:test-6x:integrationTest --info
      - name: Integration tests 7x
        uses: gradle/gradle-build-action@v2.3.0
        with:
          arguments: :c4a-test:test-7x:integrationTest --info